# Generated by Django 5.1.3 on 2024-12-25 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
